apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "validate-resource-name"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["*"]
      apiVersions: ["*"]
      operations: ["CREATE", "UPDATE"]
      resources: ["*"]
  validations:
    - expression: "!string(object.metadata.name).matches('(?i).*suyiiyii.*')"
      message: "资源名称中不允许包含 'suyiiyii'，当前名称: {{ object.metadata.name }}"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "validate-resource-name-binding"
spec:
  policyName: "validate-resource-name"
  validationActions: ["Deny"]
  matchResources:
    namespaceSelector:
      matchLabels: {}
